# DB
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
server.port=${SERVER_PORT}

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Wait for database to be ready
spring.datasource.hikari.initialization-fail-timeout=60000