# DB
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=anna
spring.datasource.password=
server.port=8083

# H2 Console
spring.h2.console.enabled=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true